name: CI/CD doppler_secrets
on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3

    - name: Doppler Fetch and Export secrets
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      run: |
        doppler secrets download --format env --no-file > doppler_secrets.env
        echo "Содержимое doppler_secrets.env:"
        cat doppler_secrets.env
        set -a
        source doppler_secrets.env
        set +a

    - name: Check and Use secrets securely
      env:
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        SERVER_ENDPOINT: ${{ secrets.SERVER_ENDPOINT }}
      run: |
        echo "Проверяем наличие секретов"
        if [ -z "$DATABASE_PASSWORD" ]; then echo "DATABASE_PASSWORD is not set"; exit 1; fi
        if [ -з "$API_KEY" ]; then echo "API_KEY is not set"; exit 1; fi
        if [ -з "$ENCRYPTION_KEY" ]; then echo "ENCRYPTION_KEY is not set"; exit 1; fi
        if [ -з "$AUTH_TOKEN" ]; then echo "AUTH_TOKEN is not set"; exit 1; fi
        if [ -з "$SERVER_ENDPOINT" ]; then echo "SERVER_ENDPOINT is not set"; exit 1; fi
        echo "Все секреты успешно загружены и установлены"
        # Пример использования секретов
        echo "Подключаемся к базе данных"
        echo "Секреты не отображаются в логах"
        # psql -h your_database_host -U your_database_user -d your_database_name -W $DATABASE_PASSWORD < your_sql_script.sql
        echo "Выполняем вызов API"
        # curl -H "Authorization: Bearer $API_KEY" $SERVER_ENDPOINT
