name: CI/CD doppler_secrets

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Doppler CLI
      run: |
        sudo curl -Ls https://cli.doppler.com/install.sh | sudo sh

    - name: Doppler Fetch and Show secrets
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      run: |
        doppler secrets download --format env --no-file > doppler_secrets.env
        cat doppler_secrets.env
